### ISSUE TITLE
Export tool

### ISSUE THREAD

**Issue by bluestreak01** [NFSdb/nfsdb#13]
Create utility to export nfsdb to a delimited format, consumable by third-party import tools.

This is more formal to-do item following conversation under issue #11

**Comment by bluestreak01** [comment]
it took a while to do this, but i feel like it is properly done now. Import and export are both very fast, zero-gc and can handle unlimited amount of data.

There are some examples here: 

https://github.com/NFSdb/nfsdb/tree/master/nfsdb-examples/src/main/java/org/nfsdb/examples/io/

**Comment by sirinath** [comment]
Cool
