### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to add 2^14 Strings with index

### ISSUE THREAD

**Issue by user16558789** [NFSdb/nfsdb#30]
Hello,

I've encountered the following error on version 3.0.0-20150216.031900-5: ArrayIndexOutOfBoundsException: -64, when trying to add 2^14 (16384) elements with indexed String column. Without index everything works fine, also $int with index does work normally - unfortunately only $str/$sym seem to be queryable by key/value.

Test that reproduces the error: https://gist.github.com/user16558789/d1b0781f1d5ca21bd637

On a side note: is there a way in 3.0.0 to query by int values (like "select * from table where id = 123;")? The code in https://github.com/NFSdb/nfsdb/releases/tag/2.0.1 does not work anymore, unfortunately.

Thank you!

**Comment by bluestreak01** [comment]
hi,

thanks for your time and effort submitting the code, i can reproduce this bug as well and i'll get back to you very shortly with a fix.

Regards,
Vlad

**Comment by bluestreak01** [comment]
Fixed, many thanks for spotting!

**Comment by user16558789** [comment]
Thank you very much for your quick answer and of course also for the fix!

Could you please add the fix to the Maven repository SNAPSHOT? It would ease deployment in my case  considerably.

Thanks again!

**Comment by bluestreak01** [comment]
yes, absolutely, i'm having some technical issues with machine that does central repo deployment. As soon as they are resolved i'lll publish snapshot, which is hopefully by Weds.

Regarding query, it is in a state of flux in 3.0 as it is being re-written, but query by indexed int should be still possible, i'll cook up an example for you tomorrow.

**Comment by bluestreak01** [comment]
Hi,

here is example of looking an object up by int value from indexed column:

```java
        StringRef intCol = new StringRef("id");

        MutableIntVariableSource intId = new MutableIntVariableSource();

        //**QUERY
        // from order head by id = 123
        // **selects latest version of record with int id 123
        DataSource<Order> dsInt = new DataSourceImpl<>(
                new JournalSourceImpl(
                        new JournalDescPartitionSource(journal, false),
                        new KvIndexHeadRowSource(
                                intCol,
                                new SingleIntHashKeySource(intCol, intId),
                                1,
                                0,
                                new IntEqualsRowFilter(intCol, intId)
                        )
                )
                , new Order());

        intId.setValue(x);
        Order o = dsInt.$new().head();
```
This is quite a long-winded for now as it is temporary complexity. This structure will likely to remain for hardcore users, but there will be a layer of easy-to-use query system, which will compile into this.

**Comment by user16558789** [comment]
Thanks again for the detailed example!

After doing some benchmarks, I did choose to use indexed String column instead of Symbol or Int (for versatility and because speed is sufficient). Modifying the number of buckets reduced access time and file size enormously (from over 1TB down to just 2GB).

Is there any rule of thumb on choosing the correct size of buckets, if all keys are different and timestamp partition is not needed - e.g. classic key-value store? I did some short experiments and it seems that the optimal bucket size is c*log(n) with c ranging from 1 to 5 in my case for about 200k elements. 5 buckets were optimal for size and write speed, 25 for access speed, anything bigger or smaller was worse in both regards. Shouldn't the values be much higher than that?

Oh, and is it correct to always assume index().size() should be set to maximum length of string (number of characters of largest string)?

**Comment by bluestreak01** [comment]
Hi,

buckets() is a distribution of hashes of your strings and it works in conjunction with recordCountHint. If you don't specify buckets it will default to 0.01 * recordCountHint.

In practice this means that index will allocate space for "buckets" hashes and recordCountHint/buckets row IDs. Space consumption is primarily driven by recordCountHint.

Both buckets and recordCountHint are per partition and per journal if latter is not partitioned. Rule of thumb is that you specify most optimistic number of records in recordCountHint. I would leave buckets at default if possible.

How many transactions do you use to add 200k elements? I'm curious to see structure definition that would cause 200k rows to be persisted in 1TB of disk space

**Comment by user16558789** [comment]
I have chosen recordCountHint to be 200k, because the number of elements is known beforehand. The index given to me from outside is int, therefore the field has also size(10) and buckets(5) (from my tests).

With default bucket values the fastest process took 9 minutes for the first 10k elements, 27 minutes for the next, I think I killed it off after one or two hours before it reached 30k. Processing without saving took 4 minutes per 10k elements. To save time in finding a good bucketsize, I benchmarked only the simpler case with single index field like in the bug report, and after finding out that log(n) was a good choice, I tried it with the real data, where 10k writes now took about 30 seconds combined and did not increase at all.

I used 200k transactions, because I do these calculations and writes only once and this was the easiest way. Now that you mention it, a bulk insert would have probably been smarter, but the most time is taken up by my own calculations (4 minutes vs. 30 seconds per 10k).

My structure has a string key field, 3 int fields, a timestamp (I don't need it, but it's necessary) and a bin field for bytebuffer data. This data is normally about 2 to 40 kB per element (depending on the data, but all elements have equal size inside a single database).

**Comment by bluestreak01** [comment]
The main source of disk space consumption are transactions on index. If you were to commit in batches space and speed saving would be significant.

I took a liberty to modify example code from your bug report:

https://gist.github.com/bluestreak01/9b5bce2d585c20c4d394

Journal size produced in above case is 45MB and save time <1s

**Comment by user16558789** [comment]
Thanks for the tip, it worked really well, now the size is even smaller. I think I will change my code, because today I've processed larger data (with the 40kB elements as said before) and the needed time to save it increased linearly to about three times of what it should take judging from the smaller experiments.

I also did some benchmarks on your modified code. I did not know if your commit() on line 43 was on purpose or an oversight, so I did both, here are the results: https://gist.github.com/user16558789/a2b041d9704132d77d31

It seems smaller bucket size is still vastly superior in terms of speed and space, but I don't know why. Maybe because of the filesystem (HFS+ in my case)?

**Comment by bluestreak01** [comment]
Commit on line 43 is an oversight, sorry. Good spot though. Commit on larger bucket size is slower because with each transaction a new copy of index keys is created. In this case buckets=index keys, so more data to copy. It will be slower on any file system unfortunately.

Thank you for benchmarks, very useful!
