### ISSUE TITLE
nfsdb vs mapdb?

### ISSUE THREAD

**Issue by gembin** [NFSdb/nfsdb#32]
This is a question rather than an issue.
How it compares to https://github.com/jankotek/mapdb ?

**Comment by bluestreak01** [comment]
This is a good question. Nfsdb is not a key/value store. Data stored in tables, columns and rows.

Mapdb may be better for cases where you need map-like structure.

Nfsdb could be for cases where you already have or your system can produce vast amount of data, which needs to be analysed.

Mapdb is a mature project, whereas nfsdb is being developed.

I may be able to elaborate better if you have particular use case in mind.

**Comment by gembin** [comment]
Thanks for your answer.
I need an embeddable database with replication between nodes whereas MapDB dosen't have.
Is Nfsdb a wide column datastore like Cassandra?

**Comment by bluestreak01** [comment]
Yes, it is similar to cassandra in structure and has replication. Each column of data is stored in separate file. All java primitive types are supported as well as blobs. The code base is focused heavily on performance and it can operate most of the data outside of java heap and has minimal-to-none GC impact. 

There is also evolving zero-GC query system should you need it.

**Comment by sirinath** [comment]
If you measure maturity by effort putin to the product as of now NFSDB is about 1/3 the effort putting as MapDB in its short existance. MapDB (previous incarnation JDBM3) which has been around for longer. Since NFSDB is a lot more ambitious it will need more effort to get to maturity. I think when V3 comes out it could be considered mature enough for production. https://github.com/NFSdb/nfsdb/blob/master/roadmap.md

**Comment by gembin** [comment]
Thanks a lot!    BTW:  cqengine seems be to dead.

**Comment by sirinath** [comment]
No it is active. Release few months back and in the process of migrating to Github but I feel NFSDB may be worth the wait. Hopefully it will be faster. Definitely more functional.

**Comment by gembin** [comment]
i will try out nfsdb, thanks for your suggestion.

**Comment by sirinath** [comment]
@bluestreak01 Please make sure it will indeed be the faster on the block.

**Comment by bluestreak01** [comment]
thank Suminda, I'll do my best :)

**Comment by sirinath** [comment]
Maybe you want to track and publish speed information on regular basis. MapDB, Chronicles, Xodus, CQEngine, InfluxDB, Crate,  Aerospike vs NFSDB. This is just be keep everyone interested. It can be something simple as done in the following page: http://julialang.org/. Also need not be representative but just some important stats which can be handled by all.

**Comment by bluestreak01** [comment]
At some point, sure. Thanks for the pointers.

**Comment by bluestreak01** [comment]
Chaps, i'm closing this as I think the subject has been exhausted. Feel free to open new issue if there is something else to discuss.
