### ISSUE TITLE
Is NFSdb appropriate for JSON metrics data and time series?

### ISSUE THREAD

**Issue by bentolor** [NFSdb/nfsdb#37]
Sorry if this is not the appropriate place to discuss.

I'm working on a small, reactive metrics collector server which will collect (JSON-formed) data objects and object arrays, transform/reduce them in memory (i.e. calculate average distribution, projections, ...) and offer them through a reactive interface. On server restart I have a playback approach in mind. 

I wonder if NFSdb would be a good fit for this purpose. I like the simplicity of an embedded, file-based POJO store in NFSdb. In particular i did not find any good answers on the following questions in the documentation:

1. Is NFSdb well suited for JSON-formed data?
2. How would I limit / delete old data i.e. similar to a rolling logfile appender. I saw the partitioning feature.
3. What are the features for "time series queries" and "temporal data" of NFSdb mentioned in the wiki? The documentation left me wondering about the queries capabilities in general.

**Comment by bluestreak01** [comment]
Of course it is appropriate place.

- In current form nfsdb is not best suited to json. It can take pojos as you pointed out and i also wrote a fast parser for delimited text files (although this feature is in -beta stage). JSON is doable and i will probably write a parser for that too, but not yet.

- if your data is stamped with time and journal is partitioned, by DAY for example, data would be written to directories in YYYYMMDD format. You can delete data offline by removing older directories.

- current version has basic query functionality, there are some examples here:https://github.com/NFSdb/nfsdb/tree/master/nfsdb-examples/src/main/java/org/nfsdb/examples/query

Journal in nfsdb is append only and by nature of not overwriting information all previous versions of the same record are available to read. There are functions that allow retrieval of all or some versions of same data.

Currently developed version (3.0) expands on that and allows use of ANSI SQL to make time series queris, such as as-of join and resampling of result set. For example for journals A and B you can write queries like:

A asof join B on a.x = b.x - this will produce all events from A and events from B directly preceding in time those in A.

or

select x, avg(y) from A resample by 30m - will group records with same value of X by 30 minute interval averaging value of Y

or temporal query

A latest by X  - returns latest by time record for every value of column X

**Comment by bentolor** [comment]
Thank you @bluestreak01 for the extensive feedback!

So NFSdb has some attractive properties for our use case especially in the region "simple", "leightweight" and "fast". I'll have to look in-depth into our requirement to get a better picture if it would be a good fit for our use case.
